# Generated by Django 4.0.6 on 2022-09-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi:')),
                ('location', models.CharField(max_length=128, verbose_name='Manzili:')),
                ('old_prize', models.IntegerField(verbose_name='Eski narxi:')),
                ('new_prize', models.IntegerField(verbose_name='Yangi narxi:')),
                ('bath_room', models.IntegerField(verbose_name='Yuvinish xonalar soni:')),
                ('room', models.IntegerField(verbose_name='Mehmonxonalar soni: ')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasm yuklang:')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
