# Generated by Django 4.0.6 on 2022-09-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name_last', models.CharField(max_length=50, verbose_name='Mijoz ismi va familiyasi:')),
                ('client_position', models.CharField(max_length=40, verbose_name='Mijoz lavozimi:')),
                ('client_image', models.ImageField(upload_to='')),
                ('client_fidback', models.CharField(max_length=200, verbose_name='Mijoz fikr:')),
                ('client_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
