# Generated by Django 4.0.6 on 2022-09-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_resentblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=40, verbose_name='Agent ismi va familiyasi:')),
                ('agent_img', models.ImageField(upload_to='', verbose_name='Agent rasmini yuklang:')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
