# Generated by Django 4.0.6 on 2022-10-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerworks',
            name='area',
            field=models.FloatField(null=True, verbose_name='Umumiy maydon: '),
        ),
    ]
