# Generated by Django 4.0.6 on 2022-10-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_offerworks_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ism:', max_length=100, verbose_name='Ism:')),
                ('email', models.EmailField(help_text='Email:', max_length=254, verbose_name='Email:')),
                ('subject', models.CharField(help_text='Mavzu:', max_length=200, verbose_name='Mavzu:')),
                ('message', models.TextField(help_text='Ism:', verbose_name='Ism:')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
