# Generated by Django 4.0.6 on 2022-11-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_agents_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Foydalanuvchi ismi:')),
                ('username', models.CharField(max_length=30, verbose_name='Username:')),
                ('tg_id', models.BigIntegerField(default=1, null=True, unique=True, verbose_name='Telegram id:')),
            ],
        ),
    ]
