# Generated by Django 4.0.6 on 2022-11-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=' ', max_length=30, verbose_name='Foydalanuvchi familiyasi:'),
        ),
    ]
